# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 8100
  #配置随机端口(微服务都是使用随机端口，因为服务太多没必要去记)
  #port: ${random.int[1024,9999]}
  connection-timeout: 5000ms
  servlet:
#    context-path: /goldenhome-bootapi
    context-path: /gisapi

spring:
  # 环境 dev|test|prod
  profiles:
    active: dev
  # jackson时间格式化
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
  mvc:
    throw-exception-if-no-handler-found: true
    static-path-pattern: /static/**
  resources:
    add-mappings: false
  http:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

#mybatis
mybatis-plus:
  #dao层映射文件
  mapper-locations: classpath:mapper/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.goldenhome.modules.*.entity

#swagger设置
swagger:
  production: false
  basic:
    enable: true
    username: root
    password: root



#配置log日志存储位置
#logging:
#  path: output/logs
#实际开发中会将logs日志放在自定义的文件夹下，如下
#logging:
   #file: /user/logs/springboot.log
