# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 8100
  connection-timeout: 5000ms
  servlet:
#    context-path: /goldenhome-bootapi
    context-path: /gisapi

spring:
  # 环境 dev|test|prod
  profiles:
    active: dev
  # jackson时间格式化
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
  mvc:
    throw-exception-if-no-handler-found: true
    static-path-pattern: /static/**
  resources:
    add-mappings: false
  http:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

#mybatis
mybatis-plus:
  #dao层映射文件
  mapper-locations: classpath:mapper/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.goldenhome.modules.*.entity

#swagger设置
swagger:
  production: false
  basic:
    enable: true
    username: jpcg
    password: goldenhome